
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[364] =
    {   0,
        0,    0,   55,   54,   53,   52,   54,    2,   50,   50,
        1,   54,   54,    5,    6,    3,    4,    0,   49,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   50,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   49,    0,
       51,   50,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       21,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   51,   50,    0,
       48,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   48,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    7,   18,    0,    0,
        0,    0,    0,    0,   46,   38,    0,    0,    0,    0,
        0,    0,    0,   33,    0,    0,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   45,   26,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    8,   16,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   10,    0,    9,
        0,    0,    0,    0,    0,   47,    0,    0,    0,    0,
       12,    0,    0,    0,   32,    0,    0,    0,    0,    0,
       31,   34,    0,    0,    0,    0,    0,    0,    0,    0,
       25,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   23,    0,    0,    0,    0,    0,    0,   22,    0,
       11,   28,    0,    0,    0,    0,    0,    0,   40,    0,
        0,    0,    0,    0,   44,    0,    0,   39,    0,   13,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   43,    0,   41,    0,    0,    0,    0,    0,
        0,   35,   14,    0,    0,    0,   24,    0,    0,    0,
       15,    0,    0,    0,    0,   27,    0,   42,    0,    0,
        0,    0,    0,    0,    0,    0,   36,    0,    0,    0,
        0,    0,    0,   17,    0,    0,   20,   30,    0,   37,
        0,   29,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    1,    1,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    1,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
        1,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,    1,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,    1,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[368] =
    {   0,
        0,   62,   29, 1393, 1393, 1393,  125, 1393,    0,    3,
     1393,    2,    0, 1393, 1393, 1393, 1393,    8, 1393,  185,
        9,   22,   67,   11,   12,   70,   13,   74,   16,  186,
       68,  195,   71,  188,  191,   83,   12,   17,   10,   51,
      200,  197,  194,  227,  237,  240,  243,  244,  248,  245,
      265,  264,  249,  254,  253,  277,  282,  293,  290,  310,
      302,  305,  312,  315,  318,  319,  342,  316,  322,  356,
       31,   34,   62,   82,  348,  344,  352,  362,  370,  365,
      381,  367,  378,  377,  369,  384,  380,  395,  407,  410,
     1393,  421,  424,  423,  427,  429,  432,  430,  459,  431,

      456,  449,  473,  477,  471,  475,  483,   93,  108,  178,
     1393,  486,  489,  491,  497,  499,  525,  527,  531,  532,
      519,  534,  545,  561,  547,  551,  566,  573,  557,  372,
      560,  593,  596,  600,  611,  614,  616,  575,  590,  615,
      613,  628,  619,  643, 1393,  632,  599,  603,  658,  618,
      660,  655,  664,  665,  662,  675,  672,  671,  690,  687,
      677,  699,  704,  705,  714,  715, 1393, 1393,  717,  719,
      722,  727,  725,  742, 1393, 1393,  737,  757,  739,  754,
      765,  749,  772, 1393,  778,  779, 1393,  781,  784,  790,
      793,  818,  811,  807,  819,  808,  816, 1393, 1393,  823,

      826,  836,  832,  827,  848,  851,  862,  864,  837,  865,
      873,  875,  876,  887,  891,  890, 1393, 1393,  885,  892,
      899,  902,  911,  915,  919,  905,  927, 1393,  926, 1393,
      944,  949,  914,  947,  959, 1393,  966,  961,  965,  970,
     1393,  968,  989,  972, 1393,  979,  986,  991, 1007, 1008,
     1393, 1393, 1011, 1014, 1013,  994, 1019, 1023, 1024, 1027,
     1393, 1030, 1035, 1047, 1052, 1063, 1065, 1068, 1073, 1075,
     1074, 1393, 1087, 1076, 1081, 1090, 1086, 1093, 1393, 1088,
     1393, 1393, 1114, 1116, 1115, 1126, 1127, 1122, 1393, 1131,
     1132, 1134, 1136, 1152, 1393, 1144, 1089, 1393, 1171, 1393,

     1141, 1173, 1180, 1181, 1184, 1174, 1185, 1155, 1189, 1191,
     1194, 1199, 1393, 1201, 1393, 1214, 1227, 1223, 1217, 1229,
     1233, 1393, 1393, 1239, 1242, 1243, 1393, 1244, 1246, 1252,
     1393, 1267, 1265, 1269, 1255, 1393, 1288, 1393, 1281, 1292,
     1271, 1306, 1295, 1297, 1293, 1303, 1393, 1309, 1305, 1307,
     1311, 1320, 1332, 1393, 1339, 1335, 1393, 1393, 1346, 1393,
     1343, 1393, 1393, 1386,    0, 1388, 1390
    } ;

static const flex_int16_t yy_def[368] =
    {   0,
      364,  364,  363,  363,  363,  363,  363,  363,  365,  365,
      363,  363,  363,  363,  363,  363,  363,  366,  363,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  367,  363,  365,  363,  363,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  367,
      363,  365,  363,  363,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      363,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  363,  365,  363,
      363,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  363,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  363,  363,  366,  366,
      366,  366,  366,  366,  363,  363,  366,  366,  366,  366,
      366,  366,  366,  363,  366,  366,  363,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  363,  363,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  363,  363,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  363,  366,  363,
      366,  366,  366,  366,  366,  363,  366,  366,  366,  366,
      363,  366,  366,  366,  363,  366,  366,  366,  366,  366,
      363,  363,  366,  366,  366,  366,  366,  366,  366,  366,
      363,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  363,  366,  366,  366,  366,  366,  366,  363,  366,
      363,  363,  366,  366,  366,  366,  366,  366,  363,  366,
      366,  366,  366,  366,  363,  366,  366,  363,  366,  363,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  363,  366,  363,  366,  366,  366,  366,  366,
      366,  363,  363,  366,  366,  366,  363,  366,  366,  366,
      363,  366,  366,  366,  366,  363,  366,  363,  366,  366,
      366,  366,  366,  366,  366,  366,  363,  366,  366,  366,
      366,  366,  366,  363,  366,  366,  363,  363,  366,  363,
      366,  363,    0,  363,  363,  363,  363
    } ;

static const flex_int16_t yy_nxt[1457] =
    {   0,
       37,    5,    6,    7,    8,    9,   10,   11,   38,   38,
       39,   19,   19,   12,   19,   19,   19,   71,   71,   19,
       52,   55,   72,   72,   40,   19,   13,   51,  363,   73,
       46,   45,   58,   14,  363,   15,  108,  108,   39,  109,
      109,   12,   36,   36,   47,   36,   36,   36,   52,   55,
       36,  363,   40,  363,   13,   51,   36,   73,   46,   45,
       58,   16,   17,    5,    6,    7,    8,    9,   10,   11,
       19,   19,   47,   19,   19,   12,  363,   19,   74,   48,
      363,   53,   56,   49,   54,   18,   69,  110,   13,  363,
       57,   50,   60,   64,  111,   14,  363,   15,  108,  108,

      363,   36,   36,   12,   36,   36,   74,   48,   36,   53,
       56,   49,   54,  109,  109,  110,   13,   70,   57,   50,
       60,   64,  111,   16,   17,   18,   18,   18,   19,   18,
       18,   18,   18,   20,   21,   22,   23,   18,   24,   25,
       18,   26,   27,   18,   28,   29,   30,   18,   31,   18,
       32,   33,   18,   34,   35,   18,   18,   18,   18,   36,
       18,   20,   21,   22,   23,   18,   24,   25,   18,   26,
       27,   18,   28,   29,   30,   18,   31,   18,   32,   33,
       18,   34,   35,   18,   18,   18,   18,   18,   19,   19,
      145,   19,  363,  363,   19,   41,   42,   19,   19,   66,

       19,  363,  363,   19,   65,   43,  363,   67,   76,  363,
       44,   61,  363,   59,  363,  363,   77,   62,  145,   36,
       36,   63,   36,   41,   42,   36,   75,   66,   36,   36,
       19,   36,   65,   43,   36,   67,   76,   78,   44,   61,
       19,   59,  363,   19,   77,   62,   19,   19,   19,   63,
      363,   19,   91,   87,   75,  363,   19,   19,   79,  363,
      363,   36,   81,   93,   82,   78,   80,   19,   19,   83,
      363,   36,   84,   85,   36,   92,   86,   36,   36,   36,
       19,   87,   36,   36,   90,   19,   79,   36,   36,   88,
       81,   93,   82,   19,   80,   89,   19,   83,   36,   36,

       84,   85,   94,   92,   86,   19,  363,   95,   19,   97,
       98,   36,   90,   19,   96,   19,   36,   88,   19,   19,
      103,   19,   19,   89,   36,   19,   99,   36,  363,  102,
       94,  363,  100,  106,  101,   95,   36,   97,   98,   36,
      363,  104,   96,  105,   36,   19,   36,   19,  103,   36,
       36,   19,   36,   36,   99,   19,   36,  102,   18,   69,
      100,  106,  101,  107,  112,   19,  113,  363,   19,  104,
       19,  105,   19,   19,  115,  167,   36,  117,   36,  114,
       19,   19,   36,   19,   19,  363,   36,   19,  120,  121,
       70,  107,  112,  119,  113,  122,   36,  116,   19,   36,

      123,   36,  115,   36,   36,  117,   36,  114,  118,  124,
       19,   36,   36,   19,   36,   36,  120,  121,   36,  126,
      125,  119,  127,  122,   19,  116,   19,   19,  123,   36,
       19,  363,   19,   19,   19,   19,  118,  124,  363,  134,
      363,   36,  129,  128,   36,  132,  363,  126,  125,  130,
      127,  133,   19,  131,  137,   36,  363,   36,   36,   19,
      363,   36,   19,   36,   36,   36,   36,  134,  138,  135,
      129,  128,  363,  132,   19,  139,   19,  130,   19,  133,
       19,  131,  137,   36,  363,  141,   19,  143,  363,   19,
       36,  136,   19,   36,   19,  363,  138,  135,  142,  140,

       19,  363,   19,  139,  144,   36,  363,   36,  363,   36,
      147,   36,  148,  141,  146,  143,  363,   36,  149,  136,
       36,  363,   19,   36,  150,   36,  142,  140,   19,  155,
       19,   36,  144,   36,   19,   19,  363,   19,  147,  151,
      148,  363,  146,  153,  154,  363,  149,  152,   19,  363,
       19,  363,  150,   36,   19,  363,  157,  155,  156,   36,
       19,   36,  162,  168,   19,   36,   36,  151,   36,   19,
      158,  153,  154,  161,  363,  152,   19,  159,  175,   36,
      166,   36,  163,  363,  157,   36,  156,  160,  363,  363,
      162,   36,  164,  176,   36,   36,   19,  165,  158,   19,

       36,  161,  184,   19,  363,  159,   19,   36,  166,   36,
      163,  170,  171,  169,   19,  160,   19,   19,   19,   19,
      164,  187,   19,  172,   36,  165,  173,   36,  174,  185,
       36,   19,  178,   36,   36,   19,  179,   36,  363,  170,
      171,  169,  177,  180,  183,   36,   19,   36,   36,   36,
       36,  172,   36,   36,  173,  181,  174,  185,   19,  182,
      178,   19,   36,   19,  179,   19,   36,   19,   19,  186,
      177,  180,  183,  363,   19,   19,  189,   36,   19,  363,
      198,  363,  188,  181,  194,  190,  191,  182,  192,   36,
       19,  193,   36,   19,   36,  195,   36,  186,   36,   36,

      363,  196,  199,  197,  189,   36,   36,   19,   19,   36,
      188,   36,  194,  190,  191,  200,  192,   19,   19,  193,
       19,   36,   19,  195,   36,   19,  202,  205,   19,  196,
       19,  197,  363,   36,  363,  208,  201,  203,   36,   36,
       19,  363,   19,  200,  204,   19,  206,  363,   36,   36,
      207,   36,   19,   36,  202,  205,   36,   19,  213,   36,
       19,   36,  210,  208,  201,  203,  209,  363,   19,  211,
      216,   36,  204,   36,  206,  217,   36,  363,  207,  214,
      212,  218,   19,   36,   19,  363,  213,   19,   36,  215,
      210,   36,  363,   19,  209,  219,   19,  211,  216,   36,

      363,  363,  363,  363,  223,  220,   36,  214,  212,  221,
       19,  228,   36,   36,   19,   36,  222,  215,   36,   19,
      225,   19,   19,  219,   36,  363,  230,   36,  226,   19,
       19,  227,  223,  220,  224,   19,  229,  221,  363,   19,
       19,   36,   36,  363,  222,   36,  232,  234,  225,  231,
       36,   19,   36,   36,  236,  363,  226,   36,  233,  227,
       36,   36,  224,  240,  229,   19,   36,   19,  241,  235,
       36,   36,  239,  237,  232,  234,   19,  231,   19,   19,
      363,  363,   36,  243,  238,   36,  233,  244,   19,  363,
      245,  240,  242,   19,   19,   19,   36,  235,   36,   36,

      239,  237,  251,  363,  248,  252,  249,   36,   19,   36,
       36,  243,  238,  246,   19,  244,  247,  261,   19,   36,
      242,   36,   19,  250,   36,   36,   36,  253,  363,   19,
       19,  256,  248,   36,  249,  257,   36,  254,  258,   36,
      363,  246,  363,  363,  247,   36,  255,   19,   36,   36,
       19,  250,   19,   36,  363,  253,  259,  260,  262,  256,
       36,   36,   19,  257,   19,  254,  258,  363,   19,   19,
      263,   19,  363,   19,  255,   19,  363,  265,   36,  264,
      268,   36,   19,   36,  259,  260,  262,  271,  363,  272,
      363,  266,   19,   36,   19,   36,  270,  279,  263,   36,

       36,  267,   36,  269,   36,  265,   36,  264,  268,  363,
       19,   19,  273,   36,   19,  271,   19,   19,  363,  266,
       36,  274,   19,   36,  270,   36,  281,  282,   36,  267,
       19,  269,  276,   19,  275,  277,  363,  280,   19,  278,
      273,   36,   36,  363,  363,   36,  284,   36,   36,  274,
       19,  363,  283,   36,  285,   19,  363,   36,   36,  286,
      276,   36,  275,  277,   36,  280,   19,  278,  289,   36,
      363,   19,  363,  287,  284,  288,   19,   19,   19,  295,
      283,   36,  285,  292,   19,  291,   36,  286,  290,  298,
       19,  300,  313,   19,  363,  363,   19,   36,  363,   36,

      293,  287,   36,  288,  297,  299,  363,   36,   36,   36,
       36,  292,  296,  291,  294,   36,  290,   19,   19,   19,
       36,   36,   36,   36,   36,   19,  301,   36,  293,   19,
       19,  303,  297,  299,   19,   19,  306,   19,  363,   19,
      296,  302,  294,  307,  315,  304,  363,   19,   36,   36,
       36,  363,  310,  305,  301,   19,   36,  308,  322,  303,
       36,   36,  363,  309,  306,   36,   36,  312,   36,  302,
       36,  307,  311,  304,   19,   36,   19,   19,   36,  363,
      310,  305,  314,   19,   19,  308,   36,   19,   19,   36,
      363,  309,  323,  318,   19,  312,  320,   19,  363,  316,

      311,  317,   19,  325,  327,   36,  321,   36,   36,  319,
      314,  326,  363,  363,   36,   36,  324,   19,   36,   36,
      331,  318,  363,   36,  320,   36,   19,  316,   36,  317,
       19,  325,   19,   36,  321,   36,   19,  319,  328,  326,
      363,  329,   19,  330,  324,   19,  336,   19,   36,  338,
      363,   36,  363,  332,  335,   19,  363,   36,   19,  333,
      337,   36,  363,   36,  339,  334,  328,   36,   19,  329,
       19,  330,   19,   36,  347,  363,   36,   36,   36,  343,
       36,  332,  335,  340,   19,  342,   36,  333,  337,   36,
      341,   19,  339,  334,  363,   19,   19,  344,   19,   36,

       19,   36,  345,   36,  346,   36,   19,  343,  354,   19,
       19,  340,   19,  342,   19,   36,  348,  363,  341,  351,
      349,  363,   36,  357,  350,  344,   36,   36,  352,   36,
      345,   36,  346,  355,  353,  358,  356,   36,  360,   36,
       36,   36,   19,   36,  348,   36,  362,  351,  349,   19,
      363,  359,  350,  363,   36,  363,  352,  361,  363,  363,
      363,  355,  353,  363,  356,  363,   36,  363,  363,   36,
      363,  363,  363,   36,  363,  363,  363,   36,  363,  359,
       36,  363,  363,  363,  363,  361,    4,    4,   18,   18,
       68,   68,    3,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363
    } ;

static const flex_int16_t yy_chk[1457] =
    {   0,
      365,    1,    1,    1,    1,    1,    1,    1,   10,   10,
       12,   18,   21,    1,   24,   25,   27,   37,   37,   29,
       25,   27,   38,   38,   13,   22,    1,   24,    3,   39,
       22,   21,   29,    1,    0,    1,   71,   71,   12,   72,
       72,    1,   18,   21,   22,   24,   25,   27,   25,   27,
       29,    0,   13,    0,    1,   24,   22,   39,   22,   21,
       29,    1,    1,    2,    2,    2,    2,    2,    2,    2,
       23,   31,   22,   26,   33,    2,    0,   28,   40,   23,
        0,   26,   28,   23,   26,   36,   36,   73,    2,    0,
       28,   23,   31,   33,   74,    2,    0,    2,  108,  108,

        0,   23,   31,    2,   26,   33,   40,   23,   28,   26,
       28,   23,   26,  109,  109,   73,    2,   36,   28,   23,
       31,   33,   74,    2,    2,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,   20,   30,
      110,   34,    0,    0,   35,   20,   20,   43,   32,   35,

       42,    0,    0,   41,   34,   20,    0,   35,   42,    0,
       20,   32,    0,   30,    0,    0,   43,   32,  110,   20,
       30,   32,   34,   20,   20,   35,   41,   35,   43,   32,
       44,   42,   34,   20,   41,   35,   42,   44,   20,   32,
       45,   30,    0,   46,   43,   32,   47,   48,   50,   32,
        0,   49,   53,   50,   41,    0,   55,   54,   45,    0,
        0,   44,   47,   55,   47,   44,   46,   52,   51,   48,
        0,   45,   49,   49,   46,   54,   49,   47,   48,   50,
       56,   50,   49,   53,   52,   57,   45,   55,   54,   51,
       47,   55,   47,   59,   46,   51,   58,   48,   52,   51,

       49,   49,   56,   54,   49,   61,    0,   57,   62,   59,
       59,   56,   52,   60,   58,   63,   57,   51,   64,   68,
       63,   65,   66,   51,   59,   69,   60,   58,    0,   62,
       56,    0,   60,   66,   61,   57,   61,   59,   59,   62,
        0,   64,   58,   65,   60,   67,   63,   76,   63,   64,
       68,   75,   65,   66,   60,   77,   69,   62,   70,   70,
       60,   66,   61,   67,   75,   78,   76,    0,   80,   64,
       82,   65,   85,   79,   78,  130,   67,   80,   76,   77,
       84,   83,   75,   87,   81,    0,   77,   86,   83,   84,
       70,   67,   75,   82,   76,   85,   78,   79,   88,   80,

       86,   82,   78,   85,   79,   80,  130,   77,   81,   87,
       89,   84,   83,   90,   87,   81,   83,   84,   86,   89,
       88,   82,   90,   85,   92,   79,   94,   93,   86,   88,
       95,    0,   96,   98,  100,   97,   81,   87,    0,   98,
        0,   89,   93,   92,   90,   96,    0,   89,   88,   94,
       90,   97,  102,   95,  100,   92,    0,   94,   93,  101,
        0,   95,   99,   96,   98,  100,   97,   98,  101,   99,
       93,   92,    0,   96,  105,  102,  103,   94,  106,   97,
      104,   95,  100,  102,    0,  104,  107,  106,    0,  112,
      101,   99,  113,   99,  114,    0,  101,   99,  105,  103,

      115,    0,  116,  102,  107,  105,    0,  103,    0,  106,
      113,  104,  114,  104,  112,  106,    0,  107,  115,   99,
      112,    0,  121,  113,  116,  114,  105,  103,  117,  121,
      118,  115,  107,  116,  119,  120,    0,  122,  113,  117,
      114,    0,  112,  119,  120,    0,  115,  118,  123,    0,
      125,    0,  116,  121,  126,    0,  123,  121,  122,  117,
      129,  118,  126,  131,  124,  119,  120,  117,  122,  127,
      124,  119,  120,  125,    0,  118,  128,  124,  138,  123,
      129,  125,  127,    0,  123,  126,  122,  124,    0,    0,
      126,  129,  127,  139,  131,  124,  132,  128,  124,  133,

      127,  125,  147,  134,    0,  124,  148,  128,  129,  138,
      127,  133,  134,  132,  135,  124,  141,  136,  140,  137,
      127,  150,  143,  135,  139,  128,  136,  132,  137,  148,
      133,  142,  141,  147,  134,  146,  142,  148,    0,  133,
      134,  132,  140,  143,  146,  135,  144,  141,  136,  140,
      137,  135,  150,  143,  136,  144,  137,  148,  152,  144,
      141,  149,  142,  151,  142,  155,  146,  153,  154,  149,
      140,  143,  146,    0,  158,  157,  152,  144,  156,    0,
      161,    0,  151,  144,  157,  153,  154,  144,  155,  152,
      160,  156,  149,  159,  151,  158,  155,  149,  153,  154,

        0,  159,  162,  160,  152,  158,  157,  163,  164,  156,
      151,  161,  157,  153,  154,  163,  155,  165,  166,  156,
      169,  160,  170,  158,  159,  171,  165,  170,  173,  159,
      172,  160,    0,  162,    0,  173,  164,  166,  163,  164,
      177,    0,  179,  163,  169,  174,  171,    0,  165,  166,
      172,  169,  182,  170,  165,  170,  171,  180,  179,  173,
      178,  172,  177,  173,  164,  166,  174,    0,  181,  178,
      182,  177,  169,  179,  171,  183,  174,    0,  172,  180,
      178,  185,  186,  182,  188,    0,  179,  189,  180,  181,
      177,  178,    0,  190,  174,  186,  191,  178,  182,  181,

        0,    0,    0,    0,  191,  188,  183,  180,  178,  189,
      194,  196,  185,  186,  193,  188,  190,  181,  189,  197,
      193,  192,  195,  186,  190,    0,  200,  191,  194,  201,
      204,  195,  191,  188,  192,  203,  197,  189,    0,  202,
      209,  194,  196,    0,  190,  193,  202,  204,  193,  201,
      197,  205,  192,  195,  206,    0,  194,  200,  203,  195,
      201,  204,  192,  209,  197,  207,  203,  208,  210,  205,
      202,  209,  208,  206,  202,  204,  211,  201,  212,  213,
        0,    0,  205,  212,  207,  206,  203,  213,  219,    0,
      214,  209,  211,  216,  215,  220,  207,  205,  208,  210,

      208,  206,  221,    0,  216,  222,  219,  211,  226,  212,
      213,  212,  207,  214,  223,  213,  215,  233,  224,  219,
      211,  214,  225,  220,  216,  215,  220,  223,    0,  229,
      227,  226,  216,  221,  219,  227,  222,  224,  229,  226,
        0,  214,    0,    0,  215,  223,  225,  231,  233,  224,
      234,  220,  232,  225,    0,  223,  231,  232,  234,  226,
      229,  227,  235,  227,  238,  224,  229,    0,  239,  237,
      235,  242,    0,  240,  225,  244,    0,  238,  231,  237,
      242,  234,  246,  232,  231,  232,  234,  246,    0,  247,
        0,  239,  243,  235,  248,  238,  244,  256,  235,  239,

      237,  240,  242,  243,  240,  238,  244,  237,  242,    0,
      249,  250,  248,  246,  253,  246,  255,  254,    0,  239,
      247,  249,  257,  243,  244,  248,  258,  259,  256,  240,
      260,  243,  253,  262,  250,  254,    0,  257,  263,  255,
      248,  249,  250,    0,    0,  253,  262,  255,  254,  249,
      264,    0,  260,  257,  263,  265,    0,  258,  259,  264,
      253,  260,  250,  254,  262,  257,  266,  255,  267,  263,
        0,  268,    0,  265,  262,  266,  269,  271,  270,  274,
      260,  264,  263,  270,  275,  269,  265,  264,  268,  277,
      273,  280,  297,  276,    0,    0,  278,  266,    0,  267,

      271,  265,  268,  266,  276,  278,    0,  269,  271,  270,
      274,  270,  275,  269,  273,  275,  268,  283,  285,  284,
      277,  273,  280,  297,  276,  288,  283,  278,  271,  286,
      287,  285,  276,  278,  290,  291,  288,  292,    0,  293,
      275,  284,  273,  290,  301,  286,    0,  296,  283,  285,
      284,    0,  293,  287,  283,  294,  288,  291,  308,  285,
      286,  287,    0,  292,  288,  290,  291,  296,  292,  284,
      293,  290,  294,  286,  299,  301,  302,  306,  296,    0,
      293,  287,  299,  303,  304,  291,  294,  305,  307,  308,
        0,  292,  309,  304,  310,  296,  306,  311,    0,  302,

      294,  303,  312,  311,  314,  299,  307,  302,  306,  305,
      299,  312,    0,    0,  303,  304,  310,  316,  305,  307,
      319,  304,    0,  309,  306,  310,  318,  302,  311,  303,
      317,  311,  320,  312,  307,  314,  321,  305,  316,  312,
        0,  317,  324,  318,  310,  325,  326,  328,  316,  329,
        0,  319,    0,  320,  325,  330,    0,  318,  335,  321,
      328,  317,    0,  320,  330,  324,  316,  321,  333,  317,
      332,  318,  334,  324,  341,    0,  325,  326,  328,  335,
      329,  320,  325,  332,  339,  334,  330,  321,  328,  335,
      333,  337,  330,  324,    0,  340,  345,  337,  343,  333,

      344,  332,  339,  334,  340,  341,  346,  335,  349,  342,
      350,  332,  348,  334,  351,  339,  342,    0,  333,  345,
      343,    0,  337,  352,  344,  337,  340,  345,  346,  343,
      339,  344,  340,  350,  348,  353,  351,  346,  356,  349,
      342,  350,  355,  348,  342,  351,  361,  345,  343,  359,
        0,  355,  344,    0,  352,    0,  346,  359,    0,    0,
        0,  350,  348,    0,  351,    0,  353,    0,    0,  356,
        0,    0,    0,  355,    0,    0,    0,  361,    0,  355,
      359,    0,    0,    0,    0,  359,  364,  364,  366,  366,
      367,  367,  363,  363,  363,  363,  363,  363,  363,  363,

      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[55] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "2nd_Exc_Flex.l"
#line 2 "2nd_Exc_Flex.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include "2nd_Exc_Bison.tab.h"
    
    int line_num=1;


    void token_print(int token_id);

#line 918 "lex.yy.c"
#line 919 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "2nd_Exc_Flex.l"



#line 1140 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 364 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1393 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "2nd_Exc_Flex.l"
{return COLON;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "2nd_Exc_Flex.l"
{return COMMA;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "2nd_Exc_Flex.l"
{return OBRACKETS;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "2nd_Exc_Flex.l"
{return CBRACKETS;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "2nd_Exc_Flex.l"
{return OBRACES;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "2nd_Exc_Flex.l"
{return CBRACES;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "2nd_Exc_Flex.l"
{return LAST;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "2nd_Exc_Flex.l"
{return ACTIVE;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "2nd_Exc_Flex.l"
{return GAME_ID;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "2nd_Exc_Flex.l"
{return DRAW_ID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "2nd_Exc_Flex.l"
{return DRAW_TIME;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "2nd_Exc_Flex.l"
{return STATUS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "2nd_Exc_Flex.l"
{return DRAW_BREAK;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "2nd_Exc_Flex.l"
{return VISUAL_DRAW;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "2nd_Exc_Flex.l"
{return PRICE_POINTS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "2nd_Exc_Flex.l"
{return AMOUNT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "2nd_Exc_Flex.l"
{return WINNING_NUMBERS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "2nd_Exc_Flex.l"
{return LIST;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "2nd_Exc_Flex.l"
{return BONUS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "2nd_Exc_Flex.l"
{return PRIZE_CATEGORIES;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "2nd_Exc_Flex.l"
{return ID;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "2nd_Exc_Flex.l"
{return DIVIDENT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "2nd_Exc_Flex.l"
{return WINNERS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "2nd_Exc_Flex.l"
{return DISTRIBUTED;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "2nd_Exc_Flex.l"
{return JACKPOT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "2nd_Exc_Flex.l"
{return FIXED;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "2nd_Exc_Flex.l"
{return CATEG_TYPE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "2nd_Exc_Flex.l"
{return GAMETYPE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "2nd_Exc_Flex.l"
{return MINIMUM_DISTRIBUTED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "2nd_Exc_Flex.l"
{return WAGER_STATISTICS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "2nd_Exc_Flex.l"
{return COLUMNS;}       
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "2nd_Exc_Flex.l"
{return WAGERS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "2nd_Exc_Flex.l"
{return ADDON;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "2nd_Exc_Flex.l"
{return CONTENT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "2nd_Exc_Flex.l"
{return TOTALPAGES;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "2nd_Exc_Flex.l"
{return TOTALELEMENTS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "2nd_Exc_Flex.l"
{return NUMBEROFELEMENTS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "2nd_Exc_Flex.l"
{return SORT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "2nd_Exc_Flex.l"
{return DIRECTION;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "2nd_Exc_Flex.l"
{return PROPERTY;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "2nd_Exc_Flex.l"
{return IGNORECASE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "2nd_Exc_Flex.l"
{return NULLHANDLING;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "2nd_Exc_Flex.l"
{return DESCENDING;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "2nd_Exc_Flex.l"
{return ASCENDING;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "2nd_Exc_Flex.l"
{return FIRST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "2nd_Exc_Flex.l"
{return SIZE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "2nd_Exc_Flex.l"
{return NUMBER;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 78 "2nd_Exc_Flex.l"
{return BOOLEAN;}
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 79 "2nd_Exc_Flex.l"
{return STRING;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 80 "2nd_Exc_Flex.l"
{return INT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 81 "2nd_Exc_Flex.l"
{return DOUBLE;}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 82 "2nd_Exc_Flex.l"
{++line_num;} 
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 83 "2nd_Exc_Flex.l"
{;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 86 "2nd_Exc_Flex.l"
ECHO;
	YY_BREAK
#line 1480 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 364 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 364 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 363);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 86 "2nd_Exc_Flex.l"


int yywrap(void)
{
	return 1;
}
