//root GRAMMAR
jsonfile: OBRACKETS ruleLAST_RESULT CBRACKETS;

ruleLAST_RESULT: LAST COLON OBRACKETS ruleLAST CBRACKETS COMMA ACTIVE COLON OBRACKETS ruleACTIVE CBRACKETS;


ruleLAST: ruleLAST COMMA ruleLAST
|ruleGAME_ID
|ruleDRAW_ID
|ruleDRAW_TIME
|ruleSTATUS
|ruleDRAW_BREAK
|ruleVISUAL_DRAW
|rulePRICE_POINTS
|ruleWINNING_NUMS
|rulePRIZE_CATEG
|ruleWAGER_STATS
;

ruleGAME_ID: GAME_ID COLON GAME_ID_ATTRIBUTE;

ruleDRAW_ID: DRAW_ID COLON INT;

ruleDRAW_TIME: DRAW_TIME COLON INT;

ruleSTATUS: STATUS COLON ruleSTATUS_2;

ruleSTATUS_2: STRING
|ACTIVE;

ruleDRAW_BREAK: DRAW_BREAK COLON INT;

ruleVISUAL_DRAW: VISUAL_DRAW COLON INT;

rulePRICE_POINTS: PRICE_POINTS COLON OBRACKETS ruleAMOUNT CBRACKETS;

ruleAMOUNT: AMOUNT COLON DOUBLE;
/*-------------------------------------------------------------*/
ruleWINNING_NUMS: WINNING_NUMBERS COLON OBRACKETS ruleLIST COMMA ruleBONUS CBRACKETS;

ruleLIST: LIST COLON OBRACES INT COMMA INT COMMA INT COMMA INT COMMA INT CBRACES;

ruleBONUS: BONUS COLON OBRACES INT CBRACES;
/*-------------------------------------------------------------*/
rulePRIZE_CATEG: PRIZE_CATEGORIES COLON rulePRIZE_ARRAY;

rulePRIZE_ARRAY: OBRACES ruleFIRST_PRIZE COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES COMMA ruleREST_PRIZES CBRACES;

ruleFIRST_PRIZE: OBRACKETS ruleID_1 COMMA ruleDIVIDENT COMMA ruleWINNERS COMMA ruleDISTRIBUTED COMMA ruleJACKPOT COMMA ruleFIXED COMMA ruleCATEG_TYPE COMMA ruleGAMETYPE COMMA ruleMIN_DIS CBRACKETS;

ruleREST_PRIZES: OBRACKETS ruleID COMMA ruleDIVIDENT COMMA ruleWINNERS COMMA ruleDISTRIBUTED COMMA ruleJACKPOT COMMA ruleFIXED COMMA ruleCATEG_TYPE COMMA ruleGAMETYPE CBRACKETS;

ruleID: ID COLON INT;
ruleID_1: ID COLON INT;
ruleDIVIDENT: DIVIDENT COLON DOUBLE
ruleWINNERS: WINNERS COLON INT
ruleDISTRIBUTED: DISTRIBUTED COLON DOUBLE
ruleJACKPOT: JACKPOT COLON DOUBLE
ruleFIXED: FIXED COLON DOUBLE
ruleCATEG_TYPE: CATEG_TYPE COLON INT
ruleGAMETYPE: GAMETYPE COLON STRING
ruleMIN_DIS: MINIMUM_DISTRIBUTED COLON DOUBLE
/*-------------------------------------------------------------*/
ruleWAGER_STATS: WAGER_STATISTICS COLON OBRACKETS ruleCOLUMNS COMMA ruleWAGERS COMMA ruleADDON CBRACKETS;

ruleCOLUMNS: COLUMNS COLON INT;

ruleWAGERS: WAGERS COLON INT;

ruleADDON: ADDON COLON ruleJSONARRAY

ruleJSONARRAY: ruleEMPTYARRAY
|ruleARRAY;

ruleEMPTYARRAY OBRACES CBRACES

ruleARRAY: OBRACES ruleCONTEXT CBRACES;

ruleCONTEXT: ruleCONTEXT COMMA ruleCONTEXT
|INT
|STRING
|DOUBLE
;


ruleACTIVE: ruleACTIVE COMMA ruleACTIVE
|ruleGAME_ID
|ruleDRAW_ID
|ruleDRAW_TIME
|ruleSTATUS
|ruleDRAW_BREAK
|ruleVISUAL_DRAW
|rulePRICE_POINTS
|rulePRIZE_CATEG
|ruleWAGER_STATS
;